apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers: 
      - name: backend-feed
        image: kwamejoedev/udagram-api-feed
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: udagram-env
          - secretRef:
              name: udagramdb
        volumeMounts:
          - mountPath: "/root/.aws/"
            name: aws-env
      volumes:
        - name: aws-env
          configMap:
             name: aws-env
