# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-frontend:local Kwamejoedev/udagram-frontend
    - run: docker tag udagram-api-user Kwamejoedev/udagram-api-user
    - run: docker tag udagram-api-feed Kwamejoedev/udagram-api-feed
    - run: docker tag reverseproxy Kwamejoedev/reverseproxy
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - run: docker push Kwamejoedev/udagram-frontend
    - run: docker push Kwamejoedev/udagram-api-user
    - run: docker push Kwamejoedev/udagram-api-feed
    - run: docker push Kwamejoedev/reverseproxy
    
